schemaName: sic
dataSources:
  ds0:
    url: jdbc:mysql://10.159.0.101:3307/sic_0001?serverTimezone=UTC&useSSL=false
    username: sic
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds1:
    url: jdbc:mysql://10.159.0.103:3307/sic_0002?serverTimezone=UTC&useSSL=false
    username: sic
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds2:
    url: jdbc:mysql://10.159.0.105:3307/sic_0003?serverTimezone=UTC&useSSL=false
    username: sic
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds3:
    url: jdbc:mysql://10.159.0.107:3307/sic_0004?serverTimezone=UTC&useSSL=false
    username: sic
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  bindingTables:
  - IC_STOCK_OPER,IC_STOCK_OPER_GOODS,IC_STOCK_OPER_GOODS_INST,IC_STOCK_OPER_RELA
  - IC_SIM_CARD,IC_SIM_CARD_HIS
  - IC_GM_BOX,IC_GM_BOX_GOODS
  - IC_ACC_NBR,IC_ACC_NBR_HIS
  - IC_GM_GOODS_INST,IC_GM_GOODS_INST_HIS
  broadcastTables:
  - IC_ACC_NBR_CATG
  - IC_ACC_NBR_CLASS
  - IC_ACC_NBR_DISTRIBUTE
  - IC_ACC_NBR_RECYCLE_HIS
  - IC_ACC_NBR_STATE
  - IC_ACC_NBR_TYPE
  - IC_BASE_CARD_TYPE
  - IC_GM_GOODS_STATE
  - IC_GM_REQ_TYPE
  - IC_GM_UNIT
  - IC_HLR
  - IC_NBR_CLASS_REJUDGE
  - IC_RES_EVENT
  - IC_RES_OPERATION_TYPE
  - IC_RES_SPEC
  - IC_SIM_CARD_RECYCLE_HIS
  - IC_SIM_GEN_OPER
  - IC_SIM_GEN_OPER_DETAIL
  - IC_SIM_STATE
  - IC_SIM_TYPE
  - IC_STOCK_OPER_TYPE
  - INDIVIDUAL_DATA_RECORD_SIC
  defaultDataSourceName: ds0
  tables:
    IC_ACC_NBR:
      actualDataNodes: ds${0..3}.IC_ACC_NBR
      databaseStrategy:
        inline:
          algorithmExpression: ds${ACC_NBR_ID % 4}
          shardingColumn: ACC_NBR_ID
    IC_ACC_NBR_CONTENT_DAY:
      actualDataNodes: ds${0..3}.IC_ACC_NBR_CONTENT_DAY
      databaseStrategy:
        inline:
          algorithmExpression: ds${ORG_ID % 4}
          shardingColumn: ORG_ID
    IC_ACC_NBR_DISTRIBUTE_DETAIL:
      actualDataNodes: ds${0..3}.IC_ACC_NBR_DISTRIBUTE_DETAIL
      databaseStrategy:
        inline:
          algorithmExpression: ds${ACC_NBR_DIST_ID % 4}
          shardingColumn: ACC_NBR_DIST_ID
    IC_ACC_NBR_HIS:
      actualDataNodes: ds${0..3}.IC_ACC_NBR_HIS
      databaseStrategy:
        inline:
          algorithmExpression: ds${ACC_NBR_ID % 4}
          shardingColumn: ACC_NBR_ID
    IC_ACC_NBR_IDENTIFY:
      actualDataNodes: ds${0..3}.IC_ACC_NBR_IDENTIFY
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(IDENTIFY_VALUE.hashCode()) % 4}
          shardingColumn: IDENTIFY_VALUE
    IC_ACC_NBR_RECYCLE_DETAIL:
      actualDataNodes: ds${0..3}.IC_ACC_NBR_RECYCLE_DETAIL
      databaseStrategy:
        inline:
          algorithmExpression: ds${ACC_NBR_RECYCLE_HIS_ID % 4}
          shardingColumn: ACC_NBR_RECYCLE_HIS_ID
    IC_COUPON:
      actualDataNodes: ds${0..3}.IC_COUPON
      databaseStrategy:
        inline:
          algorithmExpression: ds${CUST_ID % 4}
          shardingColumn: CUST_ID
    IC_COUPON_IDENTIFY:
      actualDataNodes: ds${0..3}.IC_COUPON_IDENTIFY
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(IDENTIFY_VALUE.hashCode()) % 4}
          shardingColumn: IDENTIFY_VALUE
    IC_GM_BOX:
      actualDataNodes: ds${0..3}.IC_GM_BOX
      databaseStrategy:
        inline:
          algorithmExpression: ds${BOX_ID % 4}
          shardingColumn: BOX_ID
    IC_GM_BOX_GOODS:
      actualDataNodes: ds${0..3}.IC_GM_BOX_GOODS
      databaseStrategy:
        inline:
          algorithmExpression: ds${BOX_ID % 4}
          shardingColumn: BOX_ID
    IC_GM_GOODS_IDENTIFY:
      actualDataNodes: ds${0..3}.IC_GM_GOODS_IDENTIFY
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(IDENTIFY_VALUE.hashCode()) % 4}
          shardingColumn: IDENTIFY_VALUE
    IC_GM_GOODS_INST:
      actualDataNodes: ds${0..3}.IC_GM_GOODS_INST
      databaseStrategy:
        inline:
          algorithmExpression: ds${GOODS_ID % 4}
          shardingColumn: GOODS_ID
    IC_GM_GOODS_INST_HIS:
      actualDataNodes: ds${0..3}.IC_GM_GOODS_INST_HIS
      databaseStrategy:
        inline:
          algorithmExpression: ds${GOODS_ID % 4}
          shardingColumn: GOODS_ID
    IC_LOCATION_CONTENT_HIS:
      actualDataNodes: ds${0..3}.IC_LOCATION_CONTENT_HIS
      databaseStrategy:
        inline:
          algorithmExpression: ds${LOCATION_CONTENT_ID % 4}
          shardingColumn: LOCATION_CONTENT_ID
    IC_NBR_CLASS_REJUDGE_NBR:
      actualDataNodes: ds${0..3}.IC_NBR_CLASS_REJUDGE_NBR
      databaseStrategy:
        inline:
          algorithmExpression: ds${NBR_CLASS_REJUDGE_ID % 4}
          shardingColumn: NBR_CLASS_REJUDGE_ID
    IC_SIM_CARD:
      actualDataNodes: ds${0..3}.IC_SIM_CARD
      databaseStrategy:
        inline:
          algorithmExpression: ds${SIM_CARD_ID % 4}
          shardingColumn: SIM_CARD_ID
    IC_SIM_CARD_HIS:
      actualDataNodes: ds${0..3}.IC_SIM_CARD_HIS
      databaseStrategy:
        inline:
          algorithmExpression: ds${SIM_CARD_ID % 4}
          shardingColumn: SIM_CARD_ID
    IC_SIM_CARD_IDENTIFY:
      actualDataNodes: ds${0..3}.IC_SIM_CARD_IDENTIFY
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(IDENTIFY_VALUE.hashCode()) % 4}
          shardingColumn: IDENTIFY_VALUE
    IC_SIM_CARD_RECYCLE_DETAIL:
      actualDataNodes: ds${0..3}.IC_SIM_CARD_RECYCLE_DETAIL
      databaseStrategy:
        inline:
          algorithmExpression: ds${SIM_CARD_RECYCLE_HIS_ID % 4}
          shardingColumn: SIM_CARD_RECYCLE_HIS_ID
    IC_SIM_GEN_DETAIL:
      actualDataNodes: ds${0..3}.IC_SIM_GEN_DETAIL
      databaseStrategy:
        inline:
          algorithmExpression: ds${SIM_GEN_OPER_DETAIL_ID % 4}
          shardingColumn: SIM_GEN_OPER_DETAIL_ID
    IC_STOCK_OPER:
      actualDataNodes: ds${0..3}.IC_STOCK_OPER
      databaseStrategy:
        inline:
          algorithmExpression: ds${STOCK_OPER_ID % 4}
          shardingColumn: STOCK_OPER_ID
    IC_STOCK_OPER_GOODS:
      actualDataNodes: ds${0..3}.IC_STOCK_OPER_GOODS
      databaseStrategy:
        inline:
          algorithmExpression: ds${STOCK_OPER_ID % 4}
          shardingColumn: STOCK_OPER_ID
    IC_STOCK_OPER_GOODS_INST:
      actualDataNodes: ds${0..3}.IC_STOCK_OPER_GOODS_INST
      databaseStrategy:
        inline:
          algorithmExpression: ds${STOCK_OPER_ID % 4}
          shardingColumn: STOCK_OPER_ID
    IC_STOCK_OPER_RELA:
      actualDataNodes: ds${0..3}.IC_STOCK_OPER_RELA
      databaseStrategy:
        inline:
          algorithmExpression: ds${STOCK_OPER_ID % 4}
          shardingColumn: STOCK_OPER_ID
