schemaName: balc
dataSources:
  ds0:
    url: jdbc:mysql://10.159.0.111:3307/balc_0001?serverTimezone=UTC&useSSL=false
    username: balc
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  bindingTables:
    - DUAL
