schemaName: btc
dataSources:
  ds0:
    url: jdbc:mysql://10.159.0.103:3307/btc_0001?serverTimezone=UTC&useSSL=false
    username: btc
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  bindingTables:
    - DUAL
