schemaName: rlc
dataSources:
  ds0:
    url: jdbc:mysql://10.159.0.107:3307/rlc_0001?serverTimezone=UTC&useSSL=false
    username: rlc
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds1:
    url: jdbc:mysql://10.159.0.108:3308/rlc_0002?serverTimezone=UTC&useSSL=false
    username: rlc
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  bindingTables:
  - RLC_EVENT_LOG_*,RLC_EVENT_LOG_MSG_*,RLC_RULE_LOG_*,RLC_RULE_PROCESS_LOG_*
  broadcastTables:
  - RLC_ACM
  - RLC_ACM_CATALOG
  - RLC_ACM_CONDITION
  - RLC_ACM_EVENT_DRIVE
  - RLC_ACM_FACTOR
  - RLC_ACM_RULE_EXP
  - RLC_ACM_TYPE
  - RLC_ACTION
  - RLC_ACTION_PARAM_VALUE
  - RLC_ACTION_PROCESS
  - RLC_ACTION_TYPE
  - RLC_ARRAY_MEMBER_ATTR
  - RLC_ARRAY_MEMBER_SELECTOR
  - RLC_AUDIENCE
  - RLC_AVAILABLE_OPER
  - RLC_BUSI_SN_TYPE
  - RLC_CAL_ATTR
  - RLC_CAL_EXPRESSION
  - RLC_CATALOG
  - RLC_DATA_TYPE
  - RLC_DEFAULT_ATTR
  - RLC_DEPEND_SERVICE
  - RLC_DEPEND_SERVICE_INPUT
  - RLC_DEPEND_SERVICE_OUTPUT
  - RLC_DIM
  - RLC_DIM_SERVICE
  - RLC_DYNAMIC_TAB_SCRIPT
  - RLC_ENRICH_SERVICE
  - RLC_ENRICH_SERVICE_TYPE
  - RLC_EVENT
  - RLC_EVENT_ATTR
  - RLC_EVENT_BASE
  - RLC_FIX_AVAILABLE_VALUE
  - RLC_FUNCTION
  - RLC_FUNCTION_ATTR_PARAM
  - RLC_FUNCTION_PARA_DATATYPE
  - RLC_INPUT_EVENT
  - RLC_INPUT_PARAM
  - RLC_LABEL
  - RLC_LEFT_OPERAND
  - RLC_MASKING_RULE
  - RLC_MEAS_TYPE
  - RLC_MEAS_UNIT
  - RLC_MQ_TOPIC
  - RLC_MSG_TEMPLATE
  - RLC_MSG_TEMPLATE_ATTR
  - RLC_OPERATOR
  - RLC_OPERATOR_TYPE
  - RLC_PRIORITY
  - RLC_PROCESS
  - RLC_PROCESS_CONNECT
  - RLC_PROCESS_FIX_OUTPUT
  - RLC_PROCESS_TYPE
  - RLC_PROMPT_TYPE
  - RLC_REG_SERVICE
  - RLC_RESP_MSG_PROCESS
  - RLC_RIGHT_OPERAND
  - RLC_RTN_PARAM_FIELD
  - RLC_RTN_PARAM_PROCESS
  - RLC_RTN_PARAM_VALUE
  - RLC_RULE
  - RLC_RULE_CONDITION
  - RLC_RULE_FILTER
  - RLC_RULE_LABEL
  - RLC_RULE_PROCESS
  - RLC_RULE_VERSION
  - RLC_SELECTOR_FILTER
  - RLC_SERV_RTN
  - RLC_TEMPLATE_CONTENT
  - RLC_TEMPLATE_LABEL
  defaultDataSourceName: ds0
  tables:
    RLC_ACM_INST:
      actualDataNodes: ds${0..1}.RLC_ACM_INST
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(KEYFIELD_VALUE) % 2}
          shardingColumn: KEYFIELD_VALUE
    RLC_EVENT_LOG:
      actualDataNodes: ds${0..1}.RLC_EVENT_LOG
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(EVENT_LOG_ID) % 2}
          shardingColumn: EVENT_LOG_ID
    RLC_EVENT_LOG_*:
      actualDataNodes: ds${0..1}.RLC_EVENT_LOG_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(EVENT_LOG_ID) % 2}
          shardingColumn: EVENT_LOG_ID
    RLC_EVENT_LOG_MSG:
      actualDataNodes: ds${0..1}.RLC_EVENT_LOG_MSG
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(EVENT_LOG_ID) % 2}
          shardingColumn: EVENT_LOG_ID
    RLC_EVENT_LOG_MSG_*:
      actualDataNodes: ds${0..1}.RLC_EVENT_LOG_MSG_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(EVENT_LOG_ID) % 2}
          shardingColumn: EVENT_LOG_ID
    RLC_RULE_LOG:
      actualDataNodes: ds${0..1}.RLC_RULE_LOG
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(EVENT_LOG_ID) % 2}
          shardingColumn: EVENT_LOG_ID
    RLC_RULE_LOG_*:
      actualDataNodes: ds${0..1}.RLC_RULE_LOG_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(EVENT_LOG_ID) % 2}
          shardingColumn: EVENT_LOG_ID
    RLC_RULE_PROCESS_LOG:
      actualDataNodes: ds${0..1}.RLC_RULE_PROCESS_LOG
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(EVENT_LOG_ID) % 2}
          shardingColumn: EVENT_LOG_ID
    RLC_RULE_PROCESS_LOG_*:
      actualDataNodes: ds${0..1}.RLC_RULE_PROCESS_LOG_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(EVENT_LOG_ID) % 2}
          shardingColumn: EVENT_LOG_ID
