schemaName: cic
dataSources:
  ds0:
    url: jdbc:mysql://10.159.0.102:3308/cic_0001?serverTimezone=UTC&useSSL=false
    username: cic
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds1:
    url: jdbc:mysql://10.159.0.104:3308/cic_0002?serverTimezone=UTC&useSSL=false
    username: cic
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds2:
    url: jdbc:mysql://10.159.0.110:3308/cic_0003?serverTimezone=UTC&useSSL=false
    username: cic
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds3:
    url: jdbc:mysql://10.159.0.108:3308/cic_0004?serverTimezone=UTC&useSSL=false
    username: cic
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50


shardingRule:
  bindingTables:
  - CIC_CONTACT_STGY,CIC_CONTACT_STGY_LABEL,CIC_CONTACT_STGY_TPL
  broadcastTables:
  - CIC_ACM
  - CIC_ACM_CATALOG
  - CIC_ACM_CONDITION
  - CIC_ACM_EVENT_DRIVE
  - CIC_ACM_FACTOR
  - CIC_ACM_RULE_EXP
  - CIC_ACM_TYPE
  - CIC_ACTION
  - CIC_ACTION_BLACKLIST
  - CIC_ACTION_PARAM_VALUE
  - CIC_ACTION_PROCESS
  - CIC_ACTION_TYPE
  - CIC_ADDRESS_WHITELIST
  - CIC_APP_MSG_TYPE
  - CIC_ARRAY_MEMBER_ATTR
  - CIC_ARRAY_MEMBER_SELECTOR
  - CIC_AUDIENCE
  - CIC_AVAILABLE_OPER
  - CIC_BATCH_TASK_LOG
  - CIC_BUSI_SN_TYPE
  - CIC_CAL_ATTR
  - CIC_CAL_EXPRESSION
  - CIC_CATALOG
  - CIC_CLASS
  - CIC_CONTACT_TIME_WINDOW
  - CIC_CONTENT_ATTACHMENT
  - CIC_CUST_INTERACT
  - CIC_DATA_TYPE
  - CIC_DEFAULT_ATTR
  - CIC_DEPEND_SERVICE
  - CIC_DEPEND_SERVICE_INPUT
  - CIC_DEPEND_SERVICE_OUTPUT
  - CIC_DIM
  - CIC_DIM_SERVICE
  - CIC_DOMAIN_DATA
  - CIC_DOMAIN_DATA_TYPE
  - CIC_DYNAMIC_TAB_SCRIPT
  - CIC_ENRICH_SERVICE
  - CIC_EVENT
  - CIC_EVENT_BASE
  - CIC_EVENT_CLASS
  - CIC_EVENT_FLOW
  - CIC_EVENT_FLOW_SP_AUTH
  - CIC_EVENT_SPLIT_PARAM
  - CIC_FIX_AVAILABLE_VALUE
  - CIC_FLOW_FILTER
  - CIC_FLOW_LABEL
  - CIC_FLOW_VERSION
  - CIC_FUNCTION
  - CIC_FUNCTION_ATTR_PARAM
  - CIC_FUNCTION_PARA_DATATYPE
  - CIC_FUNCTION_SERV_RTN_PARAM
  - CIC_GROUP_SEND
  - CIC_INPUT_EVENT
  - CIC_INPUT_PARAM
  - CIC_INTER_EVENT_ATTR
  - CIC_INTER_RULE
  - CIC_LABEL
  - CIC_LEFT_OPERAND
  - CIC_MASKING_RULE
  - CIC_MEAS_TYPE
  - CIC_MEAS_UNIT
  - CIC_MQ_DELAY_TIME
  - CIC_MQ_TOPIC
  - CIC_MSG_AUTH_TYPE
  - CIC_MSG_BLACKLIST
  - CIC_MSG_LABEL_SPECIALLIST
  - CIC_MSG_LENGTH_LIMIT
  - CIC_MSG_ROUTING_ITEM
  - CIC_MSG_ROUTINGS
  - CIC_MSG_TEMPLATE
  - CIC_MSG_TEMPLATE_ATTR
  - CIC_OPERATOR
  - CIC_OPERATOR_TYPE
  - CIC_PROCESS
  - CIC_PROCESS_CONNECT
  - CIC_PROCESS_FIX_OUTPUT
  - CIC_PROCESS_TYPE
  - CIC_REDIRECT_PROCESS
  - CIC_REG_SERVICE
  - CIC_RELATED_EVENT
  - CIC_RESP_MSG_PROCESS
  - CIC_RIGHT_OPERAND
  - CIC_ROUTING_METHOD
  - CIC_RULE
  - CIC_RULE_FILTER
  - CIC_SCENE
  - CIC_SCENE_TYPE
  - CIC_SELECTOR_FILTER
  - CIC_SENSITIVE_WORD
  - CIC_SERV_RTN
  - CIC_SIGN
  - CIC_SOURCE_NBR
  - CIC_TEMPLATE_CONTENT
  - CIC_TEMPLATE_FUNC
  - CIC_TEMPLATE_LABEL
  - CIC_TEMPLATE_MENU
  - CIC_TEMPLATE_MENU_RULE
  - CIC_TEMPLATE_MENU_TYPE
  - INDIVIDUAL_DATA_RECORD_CIC
  defaultDataSourceName: ds0
  tables:
    CIC_ACM_INST:
      actualDataNodes: ds${0..3}.CIC_ACM_INST
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(KEYFIELD_VALUE % 4)}
          shardingColumn: KEYFIELD_VALUE
    CIC_CONTACT_CONTENT_*:
      actualDataNodes: ds${0..3}.CIC_CONTACT_CONTENT_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_CONTACT_DELAY:
      actualDataNodes: ds${0..3}.CIC_CONTACT_DELAY
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(PART_ID % 4)}
          shardingColumn: PART_ID
    CIC_CONTACT_STGY:
      actualDataNodes: ds${0..3}.CIC_CONTACT_STGY
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(OBJ_INST_ID % 4)}
          shardingColumn: OBJ_INST_ID
    CIC_CONTACT_STGY_LABEL:
      actualDataNodes: ds${0..3}.CIC_CONTACT_STGY_LABEL
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(OBJ_INST_ID % 4)}
          shardingColumn: OBJ_INST_ID
    CIC_CONTACT_STGY_TPL:
      actualDataNodes: ds${0..3}.CIC_CONTACT_STGY_TPL
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(OBJ_INST_ID % 4)}
          shardingColumn: OBJ_INST_ID
    CIC_CUST_CONTACT_*:
      actualDataNodes: ds${0..3}.CIC_CUST_CONTACT_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_CUST_CONTACT_ERR:
      actualDataNodes: ds${0..3}.CIC_CUST_CONTACT_ERR
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_CUST_LATEST_CONTACT:
      actualDataNodes: ds${0..3}.CIC_CUST_LATEST_CONTACT
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_EVENT_CONTENT_*:
      actualDataNodes: ds${0..3}.CIC_EVENT_CONTENT_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_EVENT_RECEIVED_*:
      actualDataNodes: ds${0..3}.CIC_EVENT_RECEIVED_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_EVENT_RECEIVED_SN_*:
      actualDataNodes: ds${0..3}.CIC_EVENT_RECEIVED_SN_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_EVENT_RETRY:
      actualDataNodes: ds${0..3}.CIC_EVENT_RETRY
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_FLOW_INST_*:
      actualDataNodes: ds${0..3}.CIC_FLOW_INST_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_FLOW_PROCESS_INST_*:
      actualDataNodes: ds${0..3}.CIC_FLOW_PROCESS_INST_*
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(CUST_ID % 4)}
          shardingColumn: CUST_ID
    CIC_GROUP_SEND_DETAIL:
      actualDataNodes: ds${0..3}.CIC_GROUP_SEND_DETAIL
      databaseStrategy:
        inline:
          algorithmExpression: ds${Math.abs(GROUP_SEND_DETAIL_ID % 4)}
          shardingColumn: GROUP_SEND_DETAIL_ID

