schemaName: digchan
dataSources:
  ds0:
    url: jdbc:mysql://10.159.0.104:3308/digchan_0001?serverTimezone=UTC&useSSL=false
    username: digchan
    password: 1jian8Shu)
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  bindingTables:
    - DUAL
